### PR TITLE
Adds XR_HTCX_vive_tracker_interaction extension, demo demonstrating use

### PR DESCRIPTION
**Pull request by CharlotteGore**
Adds support for Headless OpenXR sessions and HTC Vive Trackers, which I believe demonstrates using the library in Virtual Production contexts where tracked input is required but rendering is not, or on systems where an HMD is not present.

The Vive tracker extension does add support for the function the extension adds, but doesn't demonstrate using it.

### CODE REVIEW

**Comment by CharlotteGore** [comment]
(I changed my mind on this and decided that cleaning up the PR a little bit and just leaving it for @1runeberg to decide is fine)

**Comment by 1runeberg** [comment]
> (I changed my mind on this and decided that cleaning up the PR a little bit and just leaving it for @1runeberg to decide is fine)

Great thanks! I'll have a look this weekend. Likely add it to the openxr interactions demo as well in the dev branch

**Comment by 1runeberg** [comment]
Hi @CharlotteGore,

Thanks again for your contribution. For #2 this seems to be just the tracker (no headless). I've had to make some modifications as well, here are the details:

Initial merge in: https://github.com/1runeberg/OpenXRProvider_v2/commit/ad44139634f4f9e52ac91344f0bf68e2c2dd222a
Detailed Modifications to PR here: https://github.com/1runeberg/OpenXRProvider_v2/commits/pr/htcx_tracker

This may have affected Linux builds which I noticed you've added support for. Let me know if that's the case and happy to get any fix(es) from you for the linux build as I don't have one handy for this project atm.

Cheers and thanks,
Rune

**Comment by CharlotteGore** [comment]
I'm on Windows so yeah no worries about the linux thing from me, any linux support I added wasn't intentional tbh.

I definitely prefer your approach to handling tracker action bindings btw. Thanks @1runeberg !

**Comment by 1runeberg** [comment]
Will do a headless branch as well, just found the headless code bits you have in the PR as well - I'll provide credit, but I'll rewrite from scratch just so the code path on implementing this is clearer, and not mixed with the tracker which is now merged. just for those who might stumble into this in the future trying to understand the extension. 

Thanks @CharlotteGore !

**Comment by CharlotteGore** [comment]
Honestly fine me me, I don't care about Github Contributor stats tbh, I just wanted the headless openxr session, that's it :D

**Pull request merged**
